### ISSUE TITLE
I want to run a RabbitMQ cluster reliably on K8s  - What should I consider ? 

### ISSUE THREAD

**Issue by omarelasfar** [rabbitmq/tgir#13]
Following up on this amazing [first ticket](https://github.com/rabbitmq/tgir/issues/11) for the topic. 

RabbitMQ runs also in a cluster. Kubernetes pods are unpredictable, What should take care of while operating a RabbitMQ cluster on K8s. 

- K8s cluster updates and RabbitMQ cluster updates (losing majoring of nodes or losing quorum) 
- Pod distribution budget and other stackset configs to be aware of.
- Simulating network partitions and needed tests to make sure the cluster is properly configured before rolling changes to a live cluster. 

![Strip-senvloer-pour-lentreprenariat-650-finalenglish1](https://user-images.githubusercontent.com/3658763/85237080-e0682c80-b423-11ea-8356-b5a64edf28b1.jpg)

**Comment by gerhard** [comment]
Hi @omarelasfar,

It was a nice surprise to find this here today, thanks for taking the time. The CommitStrip is most appreciated & fitting 😄 

How does the proposed list of topics in #14 look like to you?

**Comment by omarelasfar** [comment]
Thanks @gerhard For looking into this proposal. It took me a while searching for the most fitting CommitStrip, more time invested in the CommitStrip than the actual ticket creation :). 

Episode 06 does cover the majority of what Ifs I had in mind (Cannot see in all listed items a dedicated line item for stack sets configs /liveness and readiness probs etc). But the list is inclusive enough to provide very practical guidance on running a cluster. I think it closes this ticket and I can open a new one in case something else pops up while running a cluster.

**Comment by gerhard** [comment]
> It took me a while searching for the most fitting CommitStrip, more time invested in the CommitStrip than the actual ticket creation :)

And that's how I can tell apart those that are after quick help vs committed learning (pun intended) 🙂 

> Cannot see in all listed items a dedicated line item for stack sets configs /liveness and readiness probes etc

Good spot! I've bumped the last item and introduced readiness & liveness probes as a first topic to tackle.

> But the list is inclusive enough to provide very practical guidance on running a cluster. I think it closes this ticket and I can open a new one in case something else pops up while running a cluster.

I like your thinking 😉

**Comment by gerhard** [comment]
I had to push this back by a few days, ETA last day in September. Have a great weekend!
